apiVersion: v1
kind: Secret
metadata:
  name: aws-config-secret
type: Opaque
data:
  #considering run steps:
  #if you have a file config named `config`:
  # [default]
  # region=us-west-2
  # output=json
  # use command: cat config | base64
  # put content here:
  config: |
    W3Rlc3QKc2VjcmV0PTBdCm91dHB1dD1qc29uCm91dHB1dD1qc29u